WDS_PAP/WDS_PAP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='administrator/home.html'), name='home'),
    path('prof_add/', include('prof_add.urls')),
    path('lead_allot/', include('lead_allot.urls')),
    path('administrator/', include('administrator.urls')),


    path('chat/', include('chat.urls')),
]

urlpatterns += staticfiles_urlpatterns()

WDS_PAP/administrator/urls.py
from django.urls import path
from administrator import views


urlpatterns = [
    path('entry/', views.home, name="Entry"),
    path('leader_login/', views.home, name="Leader Login"),
    path('student_login/', views.home, name="Student Login"),
    path('admin_login/', views.home, name="Admin Login"),
    path('admin_home/<str:username>', views.admin_home, name="Admin Home"),
    path('register_gate/', views.register_gate, name="Register Gate"),
    path('register_admin', views.register_admin, name="Register Admin"),
    path('stu_pass_set/<str:username>', views.stu_pass_set, name="Default student password"),
    path('lead_allot/<str:username>', views.lead_allot, name="Leader Allotment"),
    path('assign_mentor_round_1/<str:username>', views.assign_mentor_round_1, name="Assign Mentor Round 1"),
    path('assign_mentor_round_2/<str:username>', views.assign_mentor_round_2, name="Assign Mentor Round 2"),
    path('assign_mentor_round_3/<str:username>', views.assign_mentor_round_3, name="Assign Mentor Round 3"),
    path('returned/<str:username>/', views.returned, name="Return to Admin Home"),
    path('developers/', views.developers, name="Developers"),


    path('add_stu_yes_no/', views.add_stu_yes_or_no, name="Add Students or not"),
    path('add_student/<str:username>/', views.add_student, name="Add Student"),
]

WDS_PAP/chat/urls.py
from django.urls import path, re_path
from .views import index, room


app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    re_path(r'^(?P<room_name>[^/]+)/$', room, name='room'),
]

WDS_PAP/administrator/models.py
from django.db import models

# Create your models here.


class Administrator(models.Model):
    username = models.CharField(verbose_name="Username", max_length=200)
    password = models.CharField(verbose_name="Hashed Password", max_length=500)
    is_stu_pass_set = models.BooleanField(verbose_name="Is student password set", default=False)
    is_lead_allotted = models.BooleanField(verbose_name="Are leaders allotted", default=False)
    round_1 = models.BooleanField(verbose_name="Round 1 allotment done", default=False)
    round_2 = models.BooleanField(verbose_name="Round 2 allotment done", default=False)
    round_3 = models.BooleanField(verbose_name="Round 3 allotment done", default=False)
    is_mentor_assigned = models.BooleanField(verbose_name="Is mentor assigned", default=False)

    def __str__(self):
        return self.username

WDS_PAP/administrator/views.py
from django.shortcuts import render
from prof_add.models import *
from lead_allot.models import *
from administrator.models import *
from django.contrib.auth.hashers import check_password, make_password
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
# Create your views here.


def returned(request, username):
    choice = request.POST['return']
    admin = Administrator.objects.get(username=username)
    if choice == 'return':
        return render(request, 'administrator/admin_home.html', {'admin': admin})


def home(request):
    if request.method == "POST":
        username = request.POST['username']
        i_am = request.POST['choice']
        # Administrator login
        if i_am == 'admin':
            admins = Administrator.objects.filter(username=username)
            if admins:
                admin = Administrator.objects.get(username=username)
                return render(request, 'administrator/admin_login.html', {'admin': admin})
            else:
                messages.info(request, f"User not found")
                return render(request, 'administrator/home.html', {})
        elif i_am == 'lead':
            leaders = Leader.objects.filter(reg_no=username)
            admins = Administrator.objects.all()
            admin = admins[0]
            if admin.is_lead_allotted:
                if leaders:
                    leader = leaders.get(reg_no=username)
                    return render(request, 'lead_allot/leader_login.html', {'leader': leader})
                else:
                    messages.info(request, f"User not found")
                    return render(request, 'administrator/home.html', {})
            else:  # Leaders not yet allotted.
                messages.info(request, f"Group leader login not authorised yet!")
                return render(request, 'administrator/home.html', {})
        # Student login
        else:
            students = Student.objects.filter(reg_no=username)
            admins = Administrator.objects.all()
            admin = admins[0]
            if admin.is_stu_pass_set:
                if students:
                    student = students.get(reg_no=username)
                    return render(request, 'lead_allot/student_login.html', {'student': student})
                else:
                    messages.info(request, f"User not found")
                    return render(request, 'administrator/home.html', {})
            else:  # Student password not yet set.
                messages.info(request, f"Student login not authorised yet!")
                return render(request, 'administrator/home.html', {})
    else:
        messages.info(request, f"You are not logged in")
        return render(request, 'administrator/home.html', {})


def admin_home(request, username):
    if request.method == 'POST':
        password = request.POST['admin_pass']
        admin = Administrator.objects.get(username=username)
        if check_password(password, admin.password):
            return render(request, 'administrator/admin_home.html', {'admin': admin})
        else:
            messages.info(request, f"Wrong password")
            message = "wrong Password"
            return render(request, 'administrator/admin_login.html', {'admin': admin, 'message': message})
    else:
        messages.info(request, f"You are not logged in")
        return render(request, 'administrator/home.html', {})


def register_gate(request):
    admin = Administrator.objects.all()
    if admin.count() == 0:
        return render(request, 'administrator/admin_register.html', {})
    else:
        messages.info(request, f"Admin already registered")
        return render(request, 'administrator/home.html', {})


def register_admin(request):
    username = request.POST['admin_user']
    password = request.POST['admin_pass']
    re_password = request.POST['re_admin_pass']
    if password == re_password:
        admin = Administrator(username=username, password=make_password(re_password))
        admin.save()
        messages.success(request, f"Admin registered successfully")
        return render(request, 'administrator/home.html', {})
    else:
        messages.info(request, f"Passwords did not match")
        return render(request, 'administrator/admin_register.html', {})


def stu_pass_set(request, username):
    if request.method == 'POST':
        choice = request.POST['set']
        if choice == 'yes':
            admin = Administrator.objects.get(username=username)
            students = Student.objects.all()
            if students:
                for student in students:
                    student.password = make_password(student.reg_no)
                    student.save()
                admin.is_stu_pass_set = True
                admin.save()
                messages.info(request, f"Default student password has been set")
                return render(request, 'administrator/admin_home.html', {'admin': admin})
            else:
                messages.info(request, f"No student in database yet")
                return render(request, 'administrator/admin_home.html', {'admin': admin})
    else:
        messages.info(request, f"You are not logged in")
        return render(request, 'administrator/home.html', {})


def lead_allot(request, username):
    if request.method == 'POST':
        choice = request.POST['allot']
        if choice == 'yes':
            admin = Administrator.objects.get(username=username)
            if not admin.is_lead_allotted:
                # Calculating total number of groups
                total = 0
                professors = Professor.objects.all()
                if professors:
                    for prof in professors:
                        total += prof.nog
                    # Calculated
                    students = Student.objects.all().order_by('-cpi')
                    if students:
                        i = 1
                        for student in students:
                            if i <= total:
                                lead = Leader(name=student.name, reg_no=student.reg_no, email=student.email, rank=i,
                                              password=make_password(student.reg_no))
                                i += 1
                                lead.save()
                                student.is_lead = True
                                student.save()
                                # Email notification
                                subject = 'Selected as Group Leader'
                                message = 'Hi, '+student.name+'! You have been selected as Group Leader. '
                                message += 'Your current password is your Registration Number. '
                                message += "This is a system generated Email. Don't bother replying."
                                to = student.email
                                try:
                                    send_mail(subject, message, 'ksh1998@gmail.com', [to], fail_silently=False)
                                except BadHeaderError:
                                    messages.info(request, f"Invalid Header found")
                                # Notification sent
                            else:
                                break
                        admin.is_lead_allotted = True
                        admin.save()
                        messages.success(request, f"Leaders assigned successfully")
                        return render(request, 'administrator/admin_home.html', {'admin': admin})
                    else:
                        messages.info(request, f"No student in database yet")
                        return render(request, 'administrator/admin_home.html', {'admin': admin})
                else:
                    messages.info(request, f"No professor in database yet")
                    return render(request, 'administrator/admin_home.html', {'admin': admin})
            else:
                messages.info(request, f"Leaders have already been allotted")
                return render(request, 'administrator/admin_home.html', {'admin': admin})
    else:
        messages.info(request, f"You are not logged in")
        return render(request, 'administrator/home.html', {})


def assign_mentor_round_1(request, username):
    if request.method == 'POST':
        choice = request.POST['assign1']
        if choice == 'yes':
            admin = Administrator.objects.get(username=username)
            leaders = Leader.objects.filter(has_filled_pref=True).order_by('rank')
            for leader in leaders:
                # Getting preferences
                preferences = []
                pri = ""
                for ch in leader.pref_1:
                    if ch != ',':
                        pri += ch
                    else:
                        preferences += [int(pri)]
                        break

                pri = ""
                for ch in leader.pref_2:
                    if ch != ',':
                        pri += ch
                    else:
                        preferences += [int(pri)]
                        break

                pri = ""
                for ch in leader.pref_3:
                    if ch != ',':
                        pri += ch
                    else:
                        preferences += [int(pri)]
                        break
                # Got preferences

                for pref in preferences:
                    prof = Professor.objects.get(pk=pref)
                    if prof.is_free:
                        leader.pref_allotted = str(prof.pk) + ',' + prof.name
                        prof.nog_assigned += 1
                        if prof.nog == prof.nog_assigned:
                            prof.is_free = False
                        prof.groups_assigned += str(leader.rank) + ','
                        leader.save()
                        prof.save()

WDS_PAP/administrator/templates/administrator/add_student.html
{% extends 'base.html' %}
{% comment %}
    context vars:
    admin : info of admin
{% endcomment %}

{% block title %} Add students {% endblock %}


{% block content %}
    {% comment %}
        Nav Bar
    {% endcomment %}
<div class="navbar-fixed">
    <nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo"><span style="padding-left: 50px">Project Allotment Portal</span> </a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
              <form method="post" action="{% url 'Return to Admin Home' admin.username %}">
                {% csrf_token %}
                <span style="padding-right: 50px"> <button class="btn waves-effect waves-light" type="submit" name="return" value="return">Return</button></span>
              </form>
          </li>
      </ul>
    </div>
    </nav>
</div>
    {% comment %}
        Nav bar ended
    {% endcomment %}
    <div class="container row">
        <h2>Add Student</h2>
        <form method="post" action="{% url "Add Student" admin.username%}" class="col s12">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <input type="text" id="name" name="name" required>
                    <label for="name">Name</label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">format_list_numbered</i>
                    <input type="text" id="reg_no" name="reg_no" required>
                    <label for="reg_no">Registration number</label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">school</i>
                    <input type="text" id="branch" name="branch" required>
                    <label for="branch">Branch</label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">format_list_numbered</i>
                    <input type="number" id="cpi" name="cpi" step=".01" required>
                    <label for="cpi">CPI</label>
                </div>
                <div class="input-field col s12">
                    <i class="material-icons prefix">email</i>
                    <input type="email" id="email" name="email">
                    <label for="email">Email</label>
                </div>
                <button class="btn waves-effect waves-light" type="submit">Submit
                <i class="material-icons right">send</i>
                </button>
            </div>
        </form>
    </div>
{% endblock %}

WDS_PAP/administrator/templates/administrator/admin_home.html
{% extends 'base.html' %}
{% comment %}
    context vars:
    admin : Info about logged in admin
{% endcomment %}
{% block title %}Admin Home{% endblock %}

{% block content %}
    {% comment %}
        Nav Bar
    {% endcomment %}
<div class="navbar-fixed">
    <nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo"><span style="padding-left: 50px"> Hi, {{ admin.username }}</span> </a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'home' %}"><span style="padding-right: 50px"> Logout</span></a></li>
      </ul>
    </div>
    </nav>
</div>
    {% comment %}
        Nav bar ended
    {% endcomment %}

    <div class="container">

    <h2>ADMIN ACCOUNT</h2>


    <h4>Add Professor:</h4>
    {% if admin.is_lead_allotted == True %}
        <p>Group leaders have been allotted. Professors can't be added now.</p>
    {% elif admin.round_1 == False %}
        <form method="post" action="{% url 'Yes_or_no' %}">
        {% csrf_token %}
        Do you want to add Professors?
        <button class="btn waves-effect waves-light" type="submit" name="choice" value="yes">Yes
        <i class="material-icons right">send</i>
        </button>
        </form>
    {% endif %}

    <h4>Add Students:</h4>

        <form method="post" action="{% url 'Add Students or not' %}">
        {% csrf_token %}
        Do you want to add Students?
        <button class="btn waves-effect waves-light" type="submit" name="choice_stu" value="yes">Yes
        <i class="material-icons right">send</i>
        </button>
        </form>


    <h4>Group Leader allotment:</h4>
        {% if admin.is_lead_allotted == False %}

            <form method="post" action="{% url 'Leader Allotment' admin.username %}">
                {% csrf_token %}
                Do you want to allot group leaders?
                <button class="btn waves-effect waves-light" type="submit" name="allot" value="yes">Allot
                <i class="material-icons right">send</i>
                </button>
            </form>
        {% else %}
            <p>Group Leaders have been allotted.</p>
        {% endif %}

    <h4>Default student password setting:</h4>
        {% if admin.is_stu_pass_set == False %}
            <form method="post" action="{% url 'Default student password' admin.username %}">
                {% csrf_token %}
                Do you want to Set default password for student account?
                <button class="btn waves-effect waves-light" type="submit" name="set" value="yes">Set
                <i class="material-icons right">send</i>
                </button>
            </form>
        {% else %}
            <p>Default student password has been set.</p>
        {% endif %}



    <h4>Mentor assignment:</h4>
        {% if admin.is_mentor_assigned == False and admin.is_lead_allotted == True %}
            {% if admin.round_1 == False %}

                <form method="post" action="{% url 'Assign Mentor Round 1' admin.username %}">
                    {% csrf_token %}
                    Assign mentors(Round 1):
                    <button class="btn waves-effect waves-light" type="submit" name="assign1" value="yes">Assign
                    <i class="material-icons right">send</i>
                    </button>
                </form>




{#                <p>Assign mentors(Round 1): <a href="{% url 'Assign Mentor Round 1' admin.username %}"><button class="btn waves-effect waves-light" type="submit">Assign#}
{#        <i class="material-icons right">send</i>#}
{#        </button> </a> </p>#}
            {% elif admin.round_2 == False %}

                <form method="post" action="{% url 'Assign Mentor Round 2' admin.username %}">
                    {% csrf_token %}
                    Assign mentors(Round 2):
                    <button class="btn waves-effect waves-light" type="submit" name="assign2" value="yes">Assign
                    <i class="material-icons right">send</i>
                    </button>
                </form>

{#                <p>Assign mentors(Round 2): <a href="{% url 'Assign Mentor Round 2' admin.username %}"><button class="btn waves-effect waves-light" type="submit">Assign#}
{#        <i class="material-icons right">send</i>#}
{#        </button> </a> </p>#}
            {% else %}

                <form method="post" action="{% url 'Assign Mentor Round 3' admin.username %}">
                    {% csrf_token %}
                    Assign mentors(Round 3):
                    <button class="btn waves-effect waves-light" type="submit" name="assign3" value="yes">Assign
                    <i class="material-icons right">send</i>
                    </button>
                </form>
{#                <p>Assign mentors(Round 3): <a href="{% url 'Assign Mentor Round 3' admin.username %}"><button class="btn waves-effect waves-light" type="submit">Assign#}
{#        <i class="material-icons right">send</i>#}
{#        </button> </a> </p>#}
            {% endif %}
        {% elif admin.is_mentor_assigned == False and admin.is_lead_allotted == False %}
            <p>Group Leaders not allotted yet.</p>
        {% else %}
            <p>Mentors have been assigned.</p>
        {% endif %}
    </div>

{% endblock %}

WDS_PAP/administrator/templates/administrator/admin_login.html
{% extends 'base.html' %}
{% comment %}
    context vars:
    admin : Info of current admin
{% endcomment %}
{% block title %}Admin Login{% endblock %}

{% block content %}
    {% comment %}
        Nav Bar
    {% endcomment %}
<div class="navbar-fixed">
    <nav>
    <div class="nav-wrapper">
        <a href="{% url 'home' %}" class="brand-logo"><span style="padding-left: 50px">Project Allotment Portal</span></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'home' %}"><span style="padding-right: 50px">Home Page</span></a></li>
      </ul>
    </div>
    </nav>
</div>
    {% comment %}
        Nav bar ended
    {% endcomment %}
    <div class="container">
    <h2>ADMINISTRATOR LOGIN</h2>
        <div class="row">
            <form method="post" action="{% url 'Admin Home' admin.username %}" class="col s12">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">exit_to_app</i>
                        <input type="password" id="admin_pass" name="admin_pass" required>
                        <label for="admin_pass">Password</label>
                    </div>
                    <button class="btn waves-effect waves-light" type="submit">Login
                    <i class="material-icons right">send</i>
                </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

WDS_PAP/administrator/templates/administrator/admin_register.html
{% extends 'base.html' %}

{% block title %}Register as admin{% endblock %}

{% block content %}
    {% comment %}
        Nav Bar
    {% endcomment %}
    <div class="navbar-fixed">
    <nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo"><span style="padding-left: 50px">Admin Registration</span></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'home' %}"><span style="padding-right: 50px">Home Page</span></a></li>
      </ul>
    </div>
    </nav>
    </div>
    {% comment %}
        Nav bar ended
    {% endcomment %}

    <div class="container">
    <h2>Admin Registration:</h2>
        <div class="row">
            <form method="post" action="{% url 'Register Admin' %}" class="col s12">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">account_circle</i>
                        <input type="text" id="admin_user" name="admin_user" required>
                        <label for="admin_user">Enter Username</label>
                    </div>
                    <div class="input-field col s12">
                        <i class="material-icons prefix">edit</i>
                        <input type="password" id="admin_pass" name="admin_pass" required>
                        <label for="admin_pass">Enter your password:</label>
                    </div>
                     <div class="input-field col s12">
                         <i class="material-icons prefix">autorenew</i>
                         <input type="password" id="re_admin_pass" name="re_admin_pass" required>
                         <label for="re_admin_pass">Re-enter password:</label>
                     </div>
                    <button class="btn waves-effect waves-light" type="submit">Register
            <i class="material-icons right">send</i>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

WDS_PAP/administrator/templates/administrator/home.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block title %}Home{% endblock %}
{% block content %}

    {% comment %}
        Nav Bar
    {% endcomment %}
<div class="navbar-fixed">
    <nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo"><span style="padding-left: 50px">Project Allotment Portal</span></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'chat:index' %}">Chat Room </a></li>
          <li><a href="{% url 'Register Gate' %}"><span style="padding-right: 50px"> Register as admin </span> </a> </li>
      </ul>
    </div>
    </nav>
</div>
    {% comment %}
        Nav bar ended
        <div class="parallax-container">
      <div class="parallax"><img src="{% static 'night.png' %}" alt="img"></div>
    </div>

    <div class="parallax-container">
      <div class="parallax"><img src="{% static 'img.jpeg' %}" alt="img"></div>
    </div>
{% endcomment %}





<div class="container">
<h2>Welcome to Project Allotment Portal of MNNIT.</h2>
</div>




<div class="container row">
    <h3>LOGIN HERE:</h3>
    <form method="post" action="{% url 'Entry' %}" class="col s12">
    {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <i class="material-icons prefix">account_circle</i>
                <input type="text" id="id_username" name="username" required>
                <label for="id_username">Username</label>
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">directions_walk</i>
                <label><b>Login as:</b></label>
            </div>
            <div class="input-field col s4">
                <label>
                 <input name="choice" id="admin" type="radio" value="admin" checked />
                <span>Administrator</span>
                </label>
            </div>
            <div class="input-field col s4">
                <label>
                <input name="choice" id="lead" type="radio" value="lead" />
                <span>Group Leader</span>
                </label>
            </div>
            <div class="input-field col s4">
                <label>
                <input name="choice" id="student" type="radio" value="student" />
                <span>Student</span>
                </label>
            </div>

        </div>
        <br>
        <button class="btn waves-effect waves-light" type="submit">Next
            <i class="material-icons right">send</i>
        </button>
    </form>
    <br>
</div>



{% endblock %}