quizapp/urls.py
from django.urls import path
from .import views as quizapp_views 
urlpatterns = [
    path('newhome/quiz_home',quizapp_views.quiz_home,name="quiz_home"),
	path('newhome/quiz',quizapp_views.quiz_view,name="take_quiz"),
	path('newhome/create_quiz',quizapp_views.create_quiz,name="create_quiz"),
	path('newhome/create_quiz/questions/',quizapp_views.create_questions,name="create_questions"),
	path('newhome/take_quiz/',quizapp_views.take_quiz_view,name="take_quiz_vish"),
	path('newhome/create_quiz/questions/<int:pk>/',quizapp_views.ques_detail_view,name="ques_detail"),
]

quizapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
class Quiz(models.Model):
	title = models.CharField(max_length=100)
	no_of_ques = models.PositiveIntegerField(default=0)
	time_lim = models.CharField(max_length=50)
	instructions = models.TextField()
	author  = models.ForeignKey(User,on_delete=models.DO_NOTHING)
	date_created = models.DateTimeField(default = timezone.now)
	def __str__(self):
		return "{}".format(self.title)
	class Meta:
		ordering = ['id']



class Question(models.Model):
	quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
	question = models.TextField()
	def __str__(self):
		return "{}".format(self.question)
	class Meta:
		ordering = ['id']
class Option(models.Model):
	quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
	question = models.ForeignKey(Question,on_delete=models.CASCADE)
	option1 = models.TextField()
	option2 = models.TextField()
	option3 = models.TextField(null=True,blank=True)
	option4 = models.TextField(null=True,blank=True)
	def __str__(self):
		return "{}{}{}{}".format(self.option1,self.option2,self.option3,self.option4)
	class Meta:
		ordering = ['id']
class Answer(models.Model):
	'''
		Here We have used a convention that if a question is True False Type then
		we will have option 1 set to True and option 2 set to False.
	'''
	quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
	question = models.ForeignKey(Question,on_delete=models.CASCADE)

	Ans_Choices=(('1','Option1'),('2','Option2'),('3','Option3'),('4','Option4'))
	# def Ans_Choices(que):
		# here que is quizapp.Answer.question
		# return (('1',que.objects.all()),('2','option2'),('3','option3'),('4','option4'))
	# curr_question = Question.objects.get(id=id)
	# print(que)
	# def Ans_Choices():
		# obj = Option.objects.last()
	# 	curr_question = objs
	# 	# for obj in questions:
	# 	print(obj)
		# return(('1',getattr(obj,'option1')),('1',getattr(obj,'option2')),('1',getattr(obj,'option3')),('1',getattr(obj,'option4')))




		# return (('1','option1'),('2','option2'),('3','option3'),('4','option4'))
		# question = questions.filter(id = id)
		# for question in questions:
		# 	if(que == question.question):
			# return (('1',question.option1),('2',question.option2),('3',question.option3),('4',question.option4))
	corr_answer = models.CharField(max_length=1,choices=Ans_Choices)
	extra_info = models.TextField(null=True,blank=True)
	def __str__(self):
		return "{}".format(self.question)
	class Meta:
		ordering = ['id']

quizapp/templates/quizapp/create_questions.html
{% extends 'blogapp/base.html' %}
{% load static %}
{%load quizapp_tags%}
{% block content%}
<div class="row">
<div class="col s4 m3">
  <ul id="ques_list" class="sidenav sidenav-fixed">
    <li>
    	<div class="user-view">	
      		<a href="#user"><img class="circle" src="{{ user.profile.image.url }}"></a>
      		<a href="#user"><span>Hello, {{user.first_name}}</span></a>
    	</div>
    </li>
    	<li>
    		<table>
    			<tr>
    				<th>
    					Title
    				</th>
    				<td>
    					{{quiz.title}}
    				</td>
    			</tr>
    			<tr>
    				<th>
    					Max Ques.
    				</th>
    				<td>
    					{{quiz.no_of_ques}}
    				</td>
    			</tr>
    			<tr>
    				<th>
    					Time Limit
    				</th>
    				<td>
    					{{quiz.time_lim}}
    				</td>
    			</tr>
    		</table>
    	</li>
    {%if questions %}
    	{% for question in questions %}
			<li class="ques_list_item" >
				<a id="{{question.id}}" href="{%url 'ques_detail' question.id %}" style="text-overflow:ellipsis;overflow:hidden;white-space:nowrap;">{{forloop.counter}}. {{question}}</a>
			</li>
		{%endfor%}
	{%else%}
		<li>
			<a>No Questions till now.</a>
		</li>
	{%endif%}
  </ul>
</div>
{% if que_cnt < quiz.no_of_ques %}
<div class="container col s8">
<form id="ques_form" action="">
	{%csrf_token%}
{{form_que}}
{{form_opt}}
	<div class="input-field col s12">
    <select id="id_corr_answer">
    	<option value="" disabled>Choose Correct Answer</option>
    	<option value="1">Option1</option>
    	<option value="2">Option2</option>
    	<option value="3">Option3</option>
    	<option value="4">Option4</option>
      <!-- <option value="" disabled>Choose Correct Answer</option>
      {% for x,y in form_ans.fields.corr_answer.choices %}
      {% if forloop.counter != 1 %}
      	<option value="{{x}}">{{y}}</option>
      {%endif%}
      {%endfor%} -->
    </select>
  </div>
{{form_ans.extra_info}}
   <button class="btn" type="submit" name="action">Submit Question
    	<i class="material-icons right">send</i>
  	 </button>
 </form>
</div>
{%else%}
<div class="container col s8">
	Hope You created a good Quiz.
</div>
{% endif %}
</div>

<script type="text/javascript">
 $(document).ready(function(){
             $('select').formSelect();
        });
</script>
<script type="text/javascript">
	 $(document).ready(function(){
	    $('.sidenav').sidenav();
	  });
 </script>

 <!-- jQuery Ajax Script -->
<script type="text/javascript">
	$(document).on('submit','#ques_form',function(e){
		e.preventDefault();
		var question = $('#id_question').val().trim();
    	var option1 = $('#id_option1').val().trim();
    	var option2 = $('#id_option2').val().trim();
    	var option3 = $('#id_option3').val().trim();
    	var option4 = $('#id_option4').val().trim();
    	var corr_answer = $('#id_corr_answer').val().trim();
		var extra_info = $('#id_extra_info').val().trim();
	if( question && option1 && option2 && option3 && option4 && corr_answer 
		&& extra_info ){
		// console.log(corr_answer);
		$.ajax({
			type:'POST',
			url: "{% url 'create_questions' %}",
			data:{
				question : question,
				option1: option1,
				option2: option2,
				option3: option3,
				option4: option4,
				corr_answer: corr_answer,
				extra_info: extra_info,
				csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
			},
			dataType: 'json',
			success:function(data){ // this data is what we have recieved as json 
									// response.
				if(data.question){
					appendToQuestionsMenu(data.question,data.que_cnt,data.ques_id);
					$('#ques_form').trigger("reset");
				}
				alert("Question Added!");
				if( data.que_cnt == "{{quiz.no_of_ques}}" ){
					$("#ques_form").html(`<div class="container col s8">
											Hope You created a good Quiz.
										</div>`);
					alert("Max Question Limit Reached");
				}
			}
		});
		
	}
	else{
		alert("All fields are required.");
	}
	});
// Function appendToQuestionsMenu definition

function appendToQuestionsMenu(question,cnt,id){
	// mind the ` in append function.
	$("#ques_list").append(`
        <li>
            <a  id="${id}" style="text-overflow:ellipsis;overflow:hidden;white-space:nowrap;">
            	${cnt}. ${question}
            </a>
        </li>
    `);
    var href = "questions/"+id;
    $('#'+ id).children().attr("href",href);
}

</script>
<script type="text/javascript">
	$(document).on('click','.ques_list_item',function(e){
		e.preventDefault();
		alert("Ha aha");
		var url = 'ques_detail';
		$.ajax({
			method : "POST",
			url : url,	
			data = {},
			dataType: 'json',
			success:function(data){ // this data is what we have recieved as json 
									// response.
					$("#ques_form").html(`<div class="container col s8">
											<p>${data.question}</p>
											>
											<p>HI</p>
											<p>${data.options}</p>
											<p>HIELLO</p>
											<p>${data.answer}</p>
										</div>`);
					alert("Max Question Limit Reached");
				}
		});
	});



</script>
{%endblock%}

quizapp/templates/quizapp/create_quiz.html
{%extends 'blogapp/base.html' %}
{%load static%}
{%load quizapp_tags%}
{%block content%}
<div class="container">
<div class="row">
    <form class="col s12" action="" method="post">
    	{% csrf_token %}
      <div class="row">
  		<div class="input-field col s12">
          {{form.title}}
          <label for="title">Quiz-Title</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s5">
         {{form.no_of_ques}}
          <label for="no_of_ques">No. Of Questions</label>
        </div>
        <div class="input-field col s5 right">
          {{form.time_lim}}
          <label for="tim_lim">Time Limit</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <textarea id="instructions" name ="instr" class="materialize-textarea"></textarea>
          <label for="instructions">Instructions</label>
        </div>
      </div>
      <button class="btn waves-effect waves-light" type="submit" name="action">Start Adding Questions
    	<i class="material-icons right">send</i>
  	  </button>
    </form>
</div>
<div>
{% endblock %}

quizapp/templates/quizapp/quiz.html
{% load static %}
{%load quizapp_tags%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>QUIZ</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'Bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'Bootstrap/css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'Bootstrap/css/style.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'Bootstrap/css/style.css' %}">
  <style type="text/css">
    @media (min-width: 800px) and (max-width: 850px) {
      .navbar:not(.top-nav-collapse) {
        background: #1C2331 !important;
      }
    }

  </style>
</head>

<body>
<div style="  position: fixed;
              width: -webkit-fill-available;">
    <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark scrolling-navbar" id="navSmall">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand" target="_blank">
        <strong>CC Club MNNIT</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            {%with Index="Index"%}
            <a class="nav-link wave-effect" href="{%url Index %}">Home
              <span class="sr-only">(current)</span>
            </a>
            {%endwith%}
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          
          <li class="nav-item">
              <div class="nav-link">Time Remaining :</div>
          </li>
          <li class="nav-item">
            <div id="timer" class="text-white nav-link"></div>
          </li> 
          <li class="nav-item"> 
            <div class="nav-link">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link border border-light rounded wave-effect"
              target="_blank">
              SUBMIT<i class=" mr-2"><i class="fas fa-arrow-right"></i></i>
            </a>
          </li>
        </ul>
        
      </div>
    </div>

    <!-- Dark mode -->
    <div class="theme-switch-wrapper">
        <label class="theme-switch" for="checkbox">
          <input type="checkbox" id="checkbox" />
          <div class="slider round"></div>
        </label>
      <em class="text-white">Dark Mode!</em>
   </div>
   

  </nav>
        <div class="row dark">
                <div class="col-4 mylist" id="fadeShow1">
                  <div id="list-example" class="list-group scrollspy-example1 mylist z-depth-2 text-center">
                    {% for question in questions %}
                      
                        <a class="list-group-item list-group-item-action dark2" href="#{{question.id}}">{{question.question}}</a>
                      
                    {% endfor %}
                    {% for question in questions %}
                      
                        <a class="list-group-item list-group-item-action dark2" href="#{{question.id}}">{{question.question}}</a>
                      
                    {% endfor %}
                    {% for question in questions %}
                      
                        <a class="list-group-item list-group-item-action dark2" href="#{{question.id}}">{{question.question}}</a>
                      
                    {% endfor %}
                    {% for question in questions %}
                      
                        <a class="list-group-item list-group-item-action dark2" href="#{{question.id}}">{{question.question}}</a>
                      
                    {% endfor %}
                    {% for question in questions %}
                      
                        <a class="list-group-item list-group-item-action dark2" href="#{{question.id}}">{{question.question}}</a>
                      
                    {% endfor %}
                    {% for question in questions %}
                      
                        <a class="list-group-item list-group-item-action dark2" href="#{{question.id}}">{{question.question}}</a>
                      
                    {% endfor %}
                  </div>
                </div>
                <div class="col-sm-8 mylist">
                  <div data-spy="scroll" data-target="#list-example" data-offset="0" class="z-depth-5 overflow-auto scrollspy-example">     
                  {%for question in questions %}  
                    <p id="list-item-{{forloop.counter}}">
                        <div class="container scrollbar scrollbar-primary">
                            <div class="card">
                                <div class="card-header text-center peach-gradient">
                                    Question {{forloop.counter}}
                                </div>

                                <div class="card-body dark2">
                                    <h5 class="card-title">{{question.question}}</h5>
                                    <p class="card-text">echcniekncecieocm;mc cjkeicne ccieicj?</p>
                                </div>

                                <div class="card-body dark1">
                                    <form action="#">
                                        {% get_options question as opt %}
                                          <p>
                                              <label>
                                                  <input name="group1" type="radio" />
                                                  <span>{{opt.0}}</span>
                                              </label>
                                          </p>
                                          <p>
                                              <label>
                                                  <input name="group1" type="radio" />
                                                  <span>{{opt.1}}</span>
                                              </label>
                                          </p>
                                          <p>
                                              <label>
                                                  <input name="group1" type="radio" />
                                                  <span>{{opt.2}}</span>
                                              </label>
                                          </p>
                                          <p>
                                              <label>
                                                  <input name="group1" type="radio" />
                                                  <span>{{opt.3}}</span>
                                              </label>
                                          </p>
                                        <p>
                                            <button type="submit" class="btn btn-primary border">SUBMIT</button>
                                            <button type="reset" class="btn btn-primary border">RESET</button>
                                        </p>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </p>
                  {%endfor%}                      
                  </div>
                </div>
              </div>
 </div>



</body>

</html>

quizapp/templates/quizapp/quiz_home.html
{%extends 'blogapp/base.html' %}
{%load static%}
{%load quizapp_tags%}
{%block content%}




{% if request.user.is_staff  %}



  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">CC MNNIT QUIZ PORTAL</a>
        <ul class="right hide-on-med-and-down">
          <li><a href='{% url "create_quiz" %}'>Create Quiz</a></li>
        </ul>
      </div>
    </nav>
  </div>

{% endif %}






<div class="container">
	<div class="row">
	{%for quiz in quizes%}
    <div class="col s6 m4">
      <div class="card blue-grey darken-1 col-content">
        <div class="card-content white-text">
          <span class="card-title">{{quiz.title}}</span>
         <table>
         	<tr>
         		<td>
         			No. of Questions: 
         		</td>
         		<td>
         			{{quiz.no_of_ques}}
         		</td>
         	</tr>
         	<tr>
         		<td>
         			Time:
         		</td>
         		<td>
         			{{quiz.time_lim}}
         		</td>
         	</tr>
         </table>
        </div>
        <div class="card-action">
          <a href="take_quiz/">Take Quiz</a>
          <a style="cursor: pointer;" class="activator grey-text text-darken-4 right">Instructions</a>
        </div>
        <div class="card-reveal">
	      <span class="card-title grey-text text-darken-4">Instructions<i class="material-icons right">close</i></span>
	      <p>{{quiz.instructions}}</p>
    	</div>
      </div>
    </div>

            
   {%endfor%}  
   	</div>

<div>   
{%endblock%}